#!/usr/bin/env python
from os import path, listdir
from PIL import Image

def main():
    dir_path = input('Enter dir path: ')
    if path.isdir(dir_path):
        search_for_images(dir_path)
    else:
        print('Not a directory')

def compress_image(image):
    """Where "file" is the image to be compressed."""
    Image.open(image).save(image, quality=35, optimize=True)

def search_for_images(dir_path):
    """Where "p" is the path to the directory to search."""
    for f in listdir(dir_path):
        abs_path = path.join(dir_path, f)
        if path.isfile(abs_path):
            if f.endswith(".jpg") or f.endswith(".jpeg"):
                compress_image(abs_path)
                print(f'Found image: {abs_path}')
        elif path.isdir(abs_path):
            search_for_images(abs_path)

main()
